# Generated by Django 2.0.2 on 2018-03-13 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powerName', models.CharField(max_length=100)),
                ('powerIP', models.CharField(max_length=50)),
                ('powerNumber', models.CharField(max_length=10)),
                ('powerUsername', models.CharField(max_length=50)),
                ('powerPassword', models.CharField(max_length=300)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
    ]
