# Generated by Django 2.0.2 on 2018-02-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='username',
            field=models.CharField(max_length=32),
        ),
    ]
