# Generated by Django 2.0.2 on 2018-02-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180223_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
